### PR TITLE
Change // Comments to -- Comments

### PR DESCRIPTION
**Pull request by cryticx**

### CODE REVIEW

**Comment by TheRealNin** [comment]
Could you please fix the line endings in those files? Thanks!

**Comment by DalinSeivewright** [comment]
...what line ending encoding are you expecting?

**Comment by TheRealNin** [comment]
For some reason, every file has to be rewritten by your patch. What are you using to edit?

**Comment by DalinSeivewright** [comment]
Afair,git stores the entire file so that explains why all the files his patch touches have different line endings.  I use atom.io.  i can't open it atm but I think i use unix line endings.

**Comment by TheRealNin** [comment]
Alright. The github UI doens't really tell me about line endings, but if you add w=1 to the URL you can see it's all whitespace stuff: https://github.com/TheRealNin/SiegePlusPlus/pull/10/commits/525e053ab4eedcdf0b9a06fc6e72206b78934d34?diff=split&w=1

So I'll accept this and hope we don't have this in the future.

**Pull request merged**
